/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NaranjaXBrandNFT } from "./NaranjaXBrandNFT";
export * as factories from "./factories";
export { NaranjaXBrandNFT__factory } from "./factories/NaranjaXBrandNFT__factory";
